name: ENV Demo
on: workflow_dispatch
env:
  APP_ENV: "dev"
jobs:
  env-demo:
    runs-on: ubuntu-latest
    env:
      APP_ENV: "test"
    steps:
    - name: Connecting to ENV
      env:
        APP_ENV: "prod"
      run: echo "APP in connecting to $APP_ENV"